'use strict';
// `report`: the generated inventory a project's notes point to instead of copying – backend routes
// and who calls them, UI routes, environment variables, settings keys, models and columns, oversized
// files, what could not be resolved and what was not covered – plus the checks' results.
// Part of the code-map skill (canonical copy: /shared/skills/code-map/).

const { natural } = require('./graph');

const esc = (s) => String(s === undefined || s === null ? '' : s).replace(/\|/g, '\\|');

function table(head, rows) {
  if (!rows.length) return ['_None._', ''];
  return [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map(esc).join(' | ')} |`), ''];
}

function report(map, result, meta) {
  const g = map.graph;
  const incoming = new Map();
  for (const e of g.edges) {
    const k = `${e.type}\0${e.to}`;
    incoming.set(k, (incoming.get(k) || 0) + 1);
  }
  const count = (type, id) => incoming.get(`${type}\0${id}`) || 0;
  const handler = new Map(g.edgesOf('handles').map((e) => [e.from, g.nodes.get(e.to)]));
  const lines = [`# Code map – ${meta.name}`, '',
    `Generated by code-map ${meta.version}${meta.commit ? ` at ${meta.commit}` : ''}. Do not edit by hand: every row comes from the code, by fixed rules. Lists are ordered by path, then method.`, ''];

  lines.push('## Checks', '');
  lines.push(...table(['Check', 'Fails the run', 'Findings', 'New'], Object.entries(result.byCheck).map(([id, c]) => [c.title, c.fails ? 'yes' : 'reports only', c.findings.length, c.new.length])));
  for (const [, c] of Object.entries(result.byCheck)) {
    if (!c.new.length) continue;
    lines.push(`**${c.title} – new:**`, '');
    for (const f of c.new.slice(0, 50)) lines.push(`- ${f.file ? `\`${f.file}${f.line ? `:${f.line}` : ''}\` ` : ''}${f.message}`);
    if (c.new.length > 50) lines.push(`- … ${c.new.length - 50} more`);
    lines.push('');
  }

  const routes = g.ofType('route').filter((r) => r.path).sort((a, b) => natural(a.path, b.path) || natural(a.method, b.method));
  lines.push('## Backend routes', '');
  lines.push(...table(['Method', 'Path', 'Defined at', 'Handler', 'UI calls'], routes.map((r) => {
    const h = handler.get(r.id);
    return [r.method, r.path, `${r.file}:${r.line}`, h ? h.qualified || h.name : '', count('requests', r.id)];
  })));

  const ui = g.ofType('ui-route').sort((a, b) => natural(a.path, b.path));
  lines.push('## UI routes', '');
  lines.push(...table(['Path', 'Page', 'Defined in'], ui.map((u) => [u.path, u.component || '', u.file || ''])));

  const env = g.ofType('env').sort((a, b) => natural(a.name, b.name));
  lines.push('## Environment variables', '');
  lines.push(...table(['Name', 'In an example env file', 'Read at'], env.map((v) => [v.name, v.declared ? 'yes' : 'no', count('reads-env', v.id)])));

  const settings = g.ofType('setting').sort((a, b) => natural(a.key, b.key));
  if (settings.length) {
    lines.push('## Settings keys', '');
    lines.push(...table(['Key', 'Default or declared', 'Read at'], settings.map((s) => [s.key, s.defined ? 'yes' : 'no', count('reads-setting', s.id)])));
  }

  const models = g.ofType('model').sort((a, b) => natural(a.name, b.name));
  lines.push('## Models and tables', '');
  lines.push(...table(['Model', 'Table', 'Defined at'], models.map((m) => [m.name, m.table || '', `${m.file}:${m.line}`])));
  const cols = g.ofType('column').sort((a, b) => natural(a.table, b.table) || natural(a.name, b.name));
  lines.push('### Columns', '');
  lines.push(...table(['Table', 'Column', 'Read at', 'Written at'], cols.map((c) => [c.table, c.name, count('reads-column', c.id), count('writes-column', c.id)])));

  const limit = map.config.limits.fileLines;
  const big = map.files.filter((e) => e.code && !e.sizeExempt && e.lines > limit).sort((a, b) => b.lines - a.lines);
  lines.push(`## Code files over ${limit} lines`, '', 'Largest first.', '');
  lines.push(...table(['File', 'Lines'], big.map((e) => [e.file, e.lines])));

  if (map.project) {
    const { unusedReport } = require('./unused');
    const unused = unusedReport(map);
    lines.push('## Unused code', '', 'Reports only; nothing here fails a run. `code-map unused` lists every item and what each kind leaves out.', '');
    lines.push(...table(['Kind', 'Items'], unused.kinds.map((k) => [k.title, k.items.length])));
    for (const k of unused.kinds) {
      if (!k.items.length) continue;
      lines.push(`**${k.title}:**`, '');
      for (const it of k.items.slice(0, 50)) lines.push(`- \`${it.file}${it.line ? `:${it.line}` : ''}\` ${it.message}`);
      if (k.items.length > 50) lines.push(`- … ${k.items.length - 50} more`);
      lines.push('');
    }
  }

  const unresolved = new Map();
  for (const u of g.unresolved) unresolved.set(u.kind, (unresolved.get(u.kind) || 0) + 1);
  lines.push('## Not resolved', '', 'Listed, never guessed: each is something only known at run time. `code-map show` names them per file.', '');
  lines.push(...table(['Kind', 'Count'], [...unresolved.entries()].sort((a, b) => natural(a[0], b[0]))));

  lines.push('## Coverage', '', 'What each part of the map covered in this repository. Anything not `mapped` was not checked.', '');
  lines.push(...table(['Area', 'Status'], g.coverage.slice().sort((a, b) => natural(a.area, b.area)).map((c) => [c.area, c.status])));
  return lines.join('\n');
}

module.exports = { report };
